# Generated by Django 2.0.4 on 2018-05-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_video_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='group_title',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='title',
            new_name='video_title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='pub_date',
        ),
    ]
